language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly


matrix:
  allow_failures:
    - php: 7
    - php: nightly

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: phpunit